// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ97lko_b49dldOlZDJ4Juu3R8lSu_Y8I',
    appId: '1:406140376321:web:a9554b25b7961d19f9f700',
    messagingSenderId: '406140376321',
    projectId: 'clawbox-487506',
    authDomain: 'clawbox-487506.firebaseapp.com',
    storageBucket: 'clawbox-487506.firebasestorage.app',
    measurementId: 'G-L7GF8T9MVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzG1D978-oT5fnKgtabZLeM27e0-JfB6U',
    appId: '1:406140376321:android:fe56c3fdf6a8dc32f9f700',
    messagingSenderId: '406140376321',
    projectId: 'clawbox-487506',
    storageBucket: 'clawbox-487506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvZAvz95YkBz-ryEJ1nB2zv50-QqDk6E4',
    appId: '1:406140376321:ios:18f3d748395e5371f9f700',
    messagingSenderId: '406140376321',
    projectId: 'clawbox-487506',
    storageBucket: 'clawbox-487506.firebasestorage.app',
    androidClientId: '406140376321-osplq7qhase88im4dvqvfovr1bvdmqkn.apps.googleusercontent.com',
    iosClientId: '406140376321-bb5gpgfie93bo8gg744c2d7tq77nhfjd.apps.googleusercontent.com',
    iosBundleId: 'com.teamlearners.clawbox',
  );
}
